# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: greeter.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'greeter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgreeter.proto\x12\x0cproto.schema\"3\n\x0fGreetingRequest\x12\x12\n\nsalutation\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"6\n\x10GreetingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\"&\n\x16GreetingHistoryRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\">\n\x17GreetingHistoryResponse\x12\x10\n\x08messages\x18\x01 \x03(\t\x12\x11\n\ttimestamp\x18\x02 \x03(\t2\xbb\x01\n\x07Greeter\x12K\n\x08SayHello\x12\x1d.proto.schema.GreetingRequest\x1a\x1e.proto.schema.GreetingResponse\"\x00\x12\x63\n\x12GetGreetingHistory\x12$.proto.schema.GreetingHistoryRequest\x1a%.proto.schema.GreetingHistoryResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greeter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GREETINGREQUEST']._serialized_start=31
  _globals['_GREETINGREQUEST']._serialized_end=82
  _globals['_GREETINGRESPONSE']._serialized_start=84
  _globals['_GREETINGRESPONSE']._serialized_end=138
  _globals['_GREETINGHISTORYREQUEST']._serialized_start=140
  _globals['_GREETINGHISTORYREQUEST']._serialized_end=178
  _globals['_GREETINGHISTORYRESPONSE']._serialized_start=180
  _globals['_GREETINGHISTORYRESPONSE']._serialized_end=242
  _globals['_GREETER']._serialized_start=245
  _globals['_GREETER']._serialized_end=432
# @@protoc_insertion_point(module_scope)
