# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proto.schema.greeter_pb2 as greeter__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in greeter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GreeterStub(object):
    """The Greeter service offers personalized greeting services.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/proto.schema.Greeter/SayHello',
                request_serializer=greeter__pb2.GreetingRequest.SerializeToString,
                response_deserializer=greeter__pb2.GreetingResponse.FromString,
                _registered_method=True)
        self.GetGreetingHistory = channel.unary_unary(
                '/proto.schema.Greeter/GetGreetingHistory',
                request_serializer=greeter__pb2.GreetingHistoryRequest.SerializeToString,
                response_deserializer=greeter__pb2.GreetingHistoryResponse.FromString,
                _registered_method=True)


class GreeterServicer(object):
    """The Greeter service offers personalized greeting services.
    """

    def SayHello(self, request, context):
        """Sends a personalized greeting to the client based on the provided name and language preference.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGreetingHistory(self, request, context):
        """Retrieves a summary of all greetings sent to a specific user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=greeter__pb2.GreetingRequest.FromString,
                    response_serializer=greeter__pb2.GreetingResponse.SerializeToString,
            ),
            'GetGreetingHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGreetingHistory,
                    request_deserializer=greeter__pb2.GreetingHistoryRequest.FromString,
                    response_serializer=greeter__pb2.GreetingHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.schema.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.schema.Greeter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """The Greeter service offers personalized greeting services.
    """

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.schema.Greeter/SayHello',
            greeter__pb2.GreetingRequest.SerializeToString,
            greeter__pb2.GreetingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGreetingHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.schema.Greeter/GetGreetingHistory',
            greeter__pb2.GreetingHistoryRequest.SerializeToString,
            greeter__pb2.GreetingHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
