# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: greeter.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'greeter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgreeter.proto\">\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x0e\n\x06\x66ormal\x18\x03 \x01(\x08\"3\n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\"@\n\x0eGoodbyeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x0e\n\x06\x66ormal\x18\x03 \x01(\x08\"5\n\x0fGoodbyeResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\"&\n\x16GreetingHistoryRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"?\n\x17GreetingHistoryResponse\x12\x10\n\x08messages\x18\x01 \x03(\t\x12\x12\n\ntimestamps\x18\x02 \x03(\t2\xb4\x01\n\x07Greeter\x12+\n\x08SayHello\x12\r.HelloRequest\x1a\x0e.HelloResponse\"\x00\x12\x31\n\nSayGoodbye\x12\x0f.GoodbyeRequest\x1a\x10.GoodbyeResponse\"\x00\x12I\n\x12GetGreetingHistory\x12\x17.GreetingHistoryRequest\x1a\x18.GreetingHistoryResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greeter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HELLOREQUEST']._serialized_start=17
  _globals['_HELLOREQUEST']._serialized_end=79
  _globals['_HELLORESPONSE']._serialized_start=81
  _globals['_HELLORESPONSE']._serialized_end=132
  _globals['_GOODBYEREQUEST']._serialized_start=134
  _globals['_GOODBYEREQUEST']._serialized_end=198
  _globals['_GOODBYERESPONSE']._serialized_start=200
  _globals['_GOODBYERESPONSE']._serialized_end=253
  _globals['_GREETINGHISTORYREQUEST']._serialized_start=255
  _globals['_GREETINGHISTORYREQUEST']._serialized_end=293
  _globals['_GREETINGHISTORYRESPONSE']._serialized_start=295
  _globals['_GREETINGHISTORYRESPONSE']._serialized_end=358
  _globals['_GREETER']._serialized_start=361
  _globals['_GREETER']._serialized_end=541
# @@protoc_insertion_point(module_scope)
